version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: outfit_finder
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"

  minio:
    image: minio/minio
    container_name: minio-instance
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
